channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=22.3.1
- pip:
  - mlflow==2.12.2
  - cloudpickle==2.2.1
  - numpy==1.25.2
  - packaging==21.3
  - psutil==5.9.4
  - pyyaml==6.0
  - scikit-learn==1.2.2
  - scipy==1.9.3
name: mlflow-env
